type Product = {
    id:number,
    title: string
    description: string
    data: string
    image:string
    url:string
    link:string
}

const productsArray4: Product[] = [
    {
        id:1,
        title: 'Gordon Tennant  "The Gods Disco" ',

        description: 'Hitting the contemporary dance floors after a successful spell in the late 80s and early 90s as GT Sampler, Scottish DJ and producer Gordon Tennant debuts on Whos Afraid Of 138?! with a sure-fire belter. Led by a magnificent melody that rouses listeners at every turn, The Gods Disco will turn any venue of space into a clubbers playground.',

        data: 'February 3, 2023',

        
        image:"/images/1.jpg",
        
        url:"https://wao138377.lnk.to/TheGodsDiscoAW",
        link:"news/NewsPage1"
        
    },
    {
        id:2,
        title: 'Doppenberg "Someday" ',

        description: 'A familiar face on Armin van Buurens A State Of Trance imprint and Ferry Corstens Flashover Recordings, Dutch producer Doppenberg hits the former with the awe-inspiring Someday. From the insanely energetic intro to the goosebumps-inducing breakdown that reflects his classical training, this track breathes uplifting allure and mainstage mayhem across its duration.',

        data: 'February 2, 2023',

    
        image:"/images/2.jpg",
        
        url:"https://wao138377.lnk.to/TheGodsDiscoAW",
        link:"news/NewsPage1"
        
    },
    {
        id:3,
        title: 'Armin van Buuren "Dayglow" ',

        description: 'A vocal banger taken straight from the third part of Armin van Buurens Feel Again album trilogy, Dayglow sees the five-time #1 DJ in the world join forces with Scottish singer-songwriter Stuart Crichton. Giving the the scintillating vocals the space to shine atop an energetic, wonder-laden production, this track will light up the mainstage in no time at all.',

        data: 'February 1, 2023',

        image:"/images/3.jpg",
        
        url:"https://wao138377.lnk.to/TheGodsDiscoAW",
        link:"news/NewsPage1"
        
    },
    {
        id:4,
        title: 'Kolonie "Distant Dreams" ',

        description: 'Touching down on A State of Trance for the first time, British DJ and producer Kolonie turns in an incredible label debut that occupies the borderlands in between trance and melodic techno. From the deep bass rolls and futuristic vocal presence to the arpeggiated main melody and stomping drop, Distant Dreams will make short work of any club space.',

        data: 'January 27, 2023',

        image:"/images/4.jpg",
        
        url:"https://wao138377.lnk.to/TheGodsDiscoAW",
        link:"news/NewsPage1"

    },
    {
        id:5,
        title: 'UDM  "Colorful Sunrise" ',

        description: 'Amplifying the momentum generated by his early-2022 release Tremolo, Colorful Sunrise sees Ukrainian DJ and producer UDM follow suit with a new, high-impact Whos Afraid Of 138?! release. Helmed by a melody that echoes the track title in both beauty and flair, Color Sunrise is a highly uplifting banger trance fans will welcome with open arms.',

        data: 'January 20, 2023',

        image:"/images/5.jpg",
        
        url:"https://wao138377.lnk.to/TheGodsDiscoAW",
        link:"news/NewsPage1"

    },
    {
        id:6,
        title: 'Scorz & Malou  "Love Like Were Dying" ',

        description: 'Already touted as the follow-up to Come To Life, Love Like Were Dying sees Brazilian talent Scorz team up with Malou for a wondrous, soul-searching piece on Armin van Buurens Armind label. Blessed with a composed groove, warm piano chords and a touching vocal presence, this song hits listeners right in the feels.',

        data: 'January 16, 2023',
        
        image:"/images/6.jpg",
        
        url:"https://wao138377.lnk.to/TheGodsDiscoAW",
        link:"news/NewsPage1"
    },
] 
export default productsArray4