type Product = {
    id:number,
    title: string
    description: string
    data: string
    image:string
    url:string
    link:string
}

const rp3Array: Product[] = [
    {
        id:3,
        title: 'ASOT 1106',

        description: '01 ARMIN VAN BUUREN & ROLAND CLARK - A STATE OF UNITY (ASOT YEAR MIX 2022 INTRO),02 HARDWELL - INTO THE UNKNOWN,03 GARETH EMERY & OMNIA - UNITY,04 ARMIN VAN BUUREN & FLORENTIN FEAT. JORDAN GRACE - ECHOES,05 ARMIN VAN BUUREN & SAM GRAY - HUMAN TOUCH (CLUB MIX),06 AVIRA & THE GOLDEN BOY - REACH OUT FOR YOUR LOVE (WAREHOUSE MIX),07 ABOVE & BEYOND FEAT. RICHARD BEDFORD - WITH YOUR HOPE (MAOR LEVI REMIX),08 LUMINN & NATALIE GIOIA - SHAPESHIFTERS (FSHO REMIX),09 ARMIN VAN BUUREN & COSMIC GATE - REFLEXION (ASOT 2023 ANTHEM),10 ABOVE & BEYOND - CANT SLEEP (RUBEN DE RONDE & ELEVVEN REMIX),11 THIS CULTURE - ITS NOT TOO LATE,12 KRYDER - PIECE OF ART,13 ABOVE & BEYOND AND ANAMĒ FEAT. MARTY LONGSTAFF - GRATITUDE (ANAMĒ AM MIX),14 EELKE KLEIJN - TRANSMISSION (JORIS VOORN REMIX),15 THE DUALZ - VISION,16 ARMIN VAN BUUREN & R3HAB FEAT. SIMON WARD - LOVE WE LOST (SKYTECH REMIX),17 ARMIN VAN BUUREN & BILLEN TED FEAT. JC STEWART - COME AROUND AGAIN (CLUB MIX),18 ANDREW BAYER - IF YOU LOOP IT, THEY WILL COME,19 ARMIN VAN BUUREN FEAT. MAIA WRIGHT - ONE MORE TIM,20 ARMIN VAN BUUREN - CLAP,21 ORJAN NILSEN FEAT. NAZZEREENE - DIAMONDS,22 BEN HEMSLEY - ERASE ME,23 RUBEN DE RONDE & CUBICORE - ADAMANT,24 KYAU & ALBERT - VELVET MORNING ,25 ARMIN VAN BUUREN & SHAPOV - WELCOME HOME,26 D-ANGELLO & FRANCIS AND BELLE HUMBLE - GOLD (D-ANGELO & FRANCIS FUTURE RAVE MIX),27 ARMIN VAN BUUREN - LET YOU DOWN,28 EMMA HEWITT X MARKUS SCHULZ - INTO MY ARMS,29 BIGTOPO - ANGEL,30 SCORZ FEAT. CHRIS HOWARD - UNDERWATER',

        data: 'February 3, 2023',

        image:"/images/31.jpg",
        url:"https://open.spotify.com/embed/playlist/2Ps64TVbfmfX6jxWJnlX1j?utm_source=oembed",
        link:"rpage3"
    },
    
] 
export default rp3Array