type Product = {
    id:number,
    title: string
    description: string
    data: string
    image:string
    url:string
    link:string
}

const rp5Array: Product[] = [
    {
        id:5,
        title: 'UDM: Colorful Sunrise',

        description: 'Amplifying the momentum generated by his early-2022 release Tremolo, Colorful Sunrise sees Ukrainian DJ and producer UDM follow suit with a new, high-impact Whos Afraid Of 138?! release. Helmed by a melody that echoes the track title in both beauty and flair, Color Sunrise is a highly uplifting banger trance fans will welcome with open arms.',

        data: 'January 20, 2023',

        image:"/images/23.jpg",
        url:"https://wao138375.lnk.to/ColorfulSunriseAW",
        link:"rpage5"
    },
    
] 
export default rp5Array